modLoader="javafml"
loaderVersion="[34,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/percivalalb/DoggyTalents/issues"
displayURL="https://minecraft.curseforge.com/projects/doggy-talents/"
logoFile="dt_logo.png"
[[mods]] #mandatory
    modId="doggytalents"
    version="${version}"
    updateJSONURL="https://raw.githubusercontent.com/percivalalb/DoggyTalents/1.16.x/version.json"
    displayName="Doggy Talents 2"
    credits="percivalalb,RaustBlackDragon,NovaViper"
    authors="percivalalb"
    description='''
    Turning your wolves into fun, playful dogs.
    '''
[[dependencies.doggytalents]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.doggytalents]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
