# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[25,)" #mandatory (24 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://minecraft.curseforge.com/projects/doggy-talents/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="/assets/doggytalents/textures/logo.png" #optional
# A text field displayed in the mod UI
credits="RaustBlackDragon for creating the original version, NovaViper for helping test and manage the mod" #optional
# A text field displayed in the mod UI
authors="Love, Cheese and small house plants" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="doggytalents" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Doggy Talents" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="https://raw.githubusercontent.com/percivalalb/DoggyTalents/master/version.json" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Turning your wolves into fun, playful dogs."
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.